/* ── Stock Card ──────────────────────────────── */
(function () {
  'use strict';

  /* Register view metadata */
  window.VIEWS = window.VIEWS || {};
  window.VIEWS['stock-card'] = {
    label:   'Stock Card',
    group:   'Stock',
    columns: ['Item Code', 'Description', 'Classification', 'Category', 'Brand', 'Model', 'Action'],
  };

  /* Register sample data */
  window.SAMPLE_DATA = window.SAMPLE_DATA || {};
  window.SAMPLE_DATA['stock-card'] = [
    {
      id: 'STK-001',
      cells: ['STK-001', 'Bond Paper A4 (500 sheets/ream)', 'Office Supplies', 'Paper Products', 'N/A', 'N/A'],
      details: {
        'Item Code':      'STK-001',
        'Description':    'Bond Paper A4 (500 sheets/ream)',
        'Classification': 'Office Supplies',
        'Category':       'Paper Products',
        'Brand':          'N/A',
        'Model':          'N/A',
        'Unit':           'Ream',
        'Unit Cost':      '₱220.00',
        'On-Hand Qty':    '145',
        'Reorder Level':  '50',
        'Location':       'Supply Room 1',
        'Remarks':        'Fast-moving item',
      },
    },
    {
      id: 'STK-002',
      cells: ['STK-002', 'Ballpen Black (box of 12)', 'Office Supplies', 'Writing Materials', 'Pilot', 'BPS-GP-M-B'],
      details: {
        'Item Code':      'STK-002',
        'Description':    'Ballpen Black (box of 12)',
        'Classification': 'Office Supplies',
        'Category':       'Writing Materials',
        'Brand':          'Pilot',
        'Model':          'BPS-GP-M-B',
        'Unit':           'Box',
        'Unit Cost':      '₱72.00',
        'On-Hand Qty':    '48',
        'Reorder Level':  '20',
        'Location':       'Supply Room 1',
        'Remarks':        'Standard issue',
      },
    },
    {
      id: 'STK-003',
      cells: ['STK-003', 'Correction Tape 5mm', 'Office Supplies', 'Writing Materials', 'Pentel', 'XZTL8-WX'],
      details: {
        'Item Code':      'STK-003',
        'Description':    'Correction Tape 5mm',
        'Classification': 'Office Supplies',
        'Category':       'Writing Materials',
        'Brand':          'Pentel',
        'Model':          'XZTL8-WX',
        'Unit':           'Piece',
        'Unit Cost':      '₱38.00',
        'On-Hand Qty':    '62',
        'Reorder Level':  '30',
        'Location':       'Supply Room 1',
        'Remarks':        'Regular stock',
      },
    },
    {
      id: 'STK-004',
      cells: ['STK-004', 'Stapler Heavy Duty', 'Office Equipment', 'Desk Equipment', 'Max', 'HD-50F'],
      details: {
        'Item Code':      'STK-004',
        'Description':    'Stapler Heavy Duty',
        'Classification': 'Office Equipment',
        'Category':       'Desk Equipment',
        'Brand':          'Max',
        'Model':          'HD-50F',
        'Unit':           'Piece',
        'Unit Cost':      '₱480.00',
        'On-Hand Qty':    '8',
        'Reorder Level':  '5',
        'Location':       'Supply Room 2',
        'Remarks':        'Low stock — monitor closely',
      },
    },
    {
      id: 'STK-005',
      cells: ['STK-005', 'Toner Cartridge HP 85A', 'ICT Supplies', 'Printer Consumables', 'HP', 'CE285A'],
      details: {
        'Item Code':      'STK-005',
        'Description':    'Toner Cartridge HP 85A',
        'Classification': 'ICT Supplies',
        'Category':       'Printer Consumables',
        'Brand':          'HP',
        'Model':          'CE285A',
        'Unit':           'Piece',
        'Unit Cost':      '₱2,800.00',
        'On-Hand Qty':    '12',
        'Reorder Level':  '6',
        'Location':       'IT Supply Cabinet',
        'Remarks':        'Monitor closely',
      },
    },
    {
      id: 'STK-006',
      cells: ['STK-006', 'Alcohol Ethyl 70% 1L', 'General Supplies', 'Sanitizing', 'Green Cross', 'N/A'],
      details: {
        'Item Code':      'STK-006',
        'Description':    'Alcohol Ethyl 70% 1L',
        'Classification': 'General Supplies',
        'Category':       'Sanitizing',
        'Brand':          'Green Cross',
        'Model':          'N/A',
        'Unit':           'Bottle',
        'Unit Cost':      '₱145.00',
        'On-Hand Qty':    '35',
        'Reorder Level':  '20',
        'Location':       'Supply Room 1',
        'Remarks':        'Regular replenishment required',
      },
    },
    {
      id: 'STK-007',
      cells: ['STK-007', 'Folder Long Expanding', 'Office Supplies', 'Filing Materials', 'National', 'N/A'],
      details: {
        'Item Code':      'STK-007',
        'Description':    'Folder Long Expanding',
        'Classification': 'Office Supplies',
        'Category':       'Filing Materials',
        'Brand':          'National',
        'Model':          'N/A',
        'Unit':           'Piece',
        'Unit Cost':      '₱22.00',
        'On-Hand Qty':    '200',
        'Reorder Level':  '80',
        'Location':       'Supply Room 1',
        'Remarks':        'Standard issue',
      },
    },
    {
      id: 'STK-008',
      cells: ['STK-008', 'Scotch Tape 1 inch', 'Office Supplies', 'Adhesives', '3M', 'N/A'],
      details: {
        'Item Code':      'STK-008',
        'Description':    'Scotch Tape 1 inch',
        'Classification': 'Office Supplies',
        'Category':       'Adhesives',
        'Brand':          '3M',
        'Model':          'N/A',
        'Unit':           'Roll',
        'Unit Cost':      '₱28.00',
        'On-Hand Qty':    '90',
        'Reorder Level':  '30',
        'Location':       'Supply Room 1',
        'Remarks':        'Regular stock',
      },
    },
    {
      id: 'STK-009',
      cells: ['STK-009', 'Whiteboard Marker (set of 4)', 'Office Supplies', 'Writing Materials', 'Expo', 'N/A'],
      details: {
        'Item Code':      'STK-009',
        'Description':    'Whiteboard Marker (set of 4)',
        'Classification': 'Office Supplies',
        'Category':       'Writing Materials',
        'Brand':          'Expo',
        'Model':          'N/A',
        'Unit':           'Set',
        'Unit Cost':      '₱95.00',
        'On-Hand Qty':    '22',
        'Reorder Level':  '10',
        'Location':       'Supply Room 1',
        'Remarks':        'Regular stock',
      },
    },
    {
      id: 'STK-010',
      cells: ['STK-010', 'USB Flash Drive 32GB', 'ICT Supplies', 'Storage Devices', 'Kingston', 'DataTraveler 100 G3'],
      details: {
        'Item Code':      'STK-010',
        'Description':    'USB Flash Drive 32GB',
        'Classification': 'ICT Supplies',
        'Category':       'Storage Devices',
        'Brand':          'Kingston',
        'Model':          'DataTraveler 100 G3',
        'Unit':           'Piece',
        'Unit Cost':      '₱280.00',
        'On-Hand Qty':    '18',
        'Reorder Level':  '10',
        'Location':       'IT Supply Cabinet',
        'Remarks':        'For official use only',
      },
    },
  ];
}());
